(*
(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition idEqual {A B : Set} (ident1 : A) (ident2 : B) : bool :=
  op_startypeminuserrorstar.

Definition show_symbol_description {A : Set} (sd : A) : string :=
  op_startypeminuserrorstar.

Definition symbol_compare {A B : Set} : A -> B := op_startypeminuserrorstar.

Definition show_symbol {A : Set} (sym1 : A) : string :=
  op_startypeminuserrorstar.

Definition show_raw_less {A B : Set} : A -> B := op_startypeminuserrorstar.

Definition show_raw {A B : Set} : A -> B := op_startypeminuserrorstar.

Definition digest_of_sym {A B : Set} : A -> B := op_startypeminuserrorstar.

Definition fresh {A : Set} (function_parameter : unit) : A :=
  let '_ := function_parameter in
  op_startypeminuserrorstar.

Definition fresh_pretty {A B : Set} (str : A) : B := op_startypeminuserrorstar.

Definition fresh_pretty_with_id {A B : Set} (mkStr : A) : B :=
  op_startypeminuserrorstar.

Definition fresh_object_address {A B : Set} (name1 : A) : B :=
  op_startypeminuserrorstar.

Definition fresh_funarg {A B C : Set} (loc : A) (i_value : B) : C :=
  op_startypeminuserrorstar.

Definition fresh_description {A B : Set} (sd : A) : B :=
  op_startypeminuserrorstar.

Definition set_symbol_description {A B : Set} : A -> B :=
  op_startypeminuserrorstar.

Definition from_same_translation_unit {A B : Set} (sym1 : A) (sym2 : B)
  : bool :=
  equiv_decb 0 (Stdlib.Digest.compare (digest_of_sym sym1) (digest_of_sym sym2)).

Definition symbol_description {A B : Set} : A -> B := op_startypeminuserrorstar.

Definition symbol_num {A B : Set} : A -> B := op_startypeminuserrorstar.
*)
