kind: pipeline
type: docker
name: default

steps:
  - name: rebuild-cache
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t cerberus-cache .
    when:
      event:
        - cron
      cron:
      - rebuild-cache

  - name: compile-cerberus
    image: cerberus-cache
    pull: never
    commands:
      - opam exec -- make

  - name: test-cerberus
    image: cerberus-cache
    pull: never
    commands:
      - opam exec -- dune exec coq/coqcaptest.exe

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
