FROM cerberus:deps

#COPY --chown=user1 . /home/opam/cerberus/
#RUN eval `opam env` && \
#  cd /home/opam/cerberus/ && \
#  make && \
#  make install
#COPY --chown=user1 docker_entry_point.sh /home/user1/
#RUN chmod +x docker_entry_point.sh
#WORKDIR /data

RUN echo 'export PS1="[\u@docker] \W # "' >> /home/user1/.bashrc
RUN echo 'eval $(opam env)' >> /home/user1/.bashrc

ENTRYPOINT ["bash"]
