all:
	menhir --external-tokens Core_parser_util --strict --explain --infer --ocamlc "ocamlc -I ../../_ocaml_generated/ -I ../../src/ -I ../../pprinters/" core_parser.mly

wip:
	menhir --external-tokens Core_parser_util --explain --infer --ocamlc "ocamlc -I ../../_ocaml_generated/ -I ../../src/ -I ../../pprinters/" core_parser.mly
