// TODO

#define blkcnt_t              __cerbty_blkcnt_t
#define blksize_t             __cerbty_blksize_t
#define clock_t               __cerbty_clock_t
#define clockid_t             __cerbty_clockid_t
#define dev_t                 __cerbty_dev_t
#define fsblkcnt_t            __cerbty_fsblkcnt_t
#define fsfilcnt_t            __cerbty_fsfilcnt_t
#define gid_t                 __cerbty_gid_t
#define id_t                  __cerbty_id_t
#define ino_t                 __cerbty_ino_t
#define key_t                 __cerbty_key_t
#define mode_t                __cerbty_mode_t
#define nlink_t               __cerbty_nlink_t
#define off_t                 __cerbty_off_t
#define pid_t                 __cerbty_pid_t
#define pthread_attr_t        __cerbty_pthread_attr_t
#define pthread_barrier_t     __cerbty_pthread_barrier_t
#define pthread_barrierattr_t __cerbty_pthread_barrierattr_t
#define pthread_cond_t        __cerbty_pthread_cond_t
#define pthread_condattr_t    __cerbty_pthread_condattr_t
#define pthread_key_t         __cerbty_pthread_key_t
#define pthread_mutex_t       __cerbty_pthread_mutex_t
#define pthread_mutexattr_t   __cerbty_pthread_mutexattr_t
#define pthread_once_t        __cerbty_pthread_once_t
#define pthread_rwlock_t      __cerbty_pthread_rwlock_t
#define pthread_rwlockattr_t  __cerbty_pthread_rwlockattr_t
#define pthread_spinlock_t    __cerbty_pthread_spinlock_t
#define pthread_t             __cerbty_pthread_t
#define size_t                __cerbty_size_t
#define ssize_t               __cerbty_ssize_t
#define suseconds_t           __cerbty_suseconds_t
#define time_t                __cerbty_time_t
#define timer_t               __cerbty_timer_t
#define trace_attr_t          __cerbty_trace_attr_t
#define trace_event_id_t      __cerbty_trace_event_id_t
#define trace_event_set_t     __cerbty_trace_event_set_t
#define trace_id_t            __cerbty_trace_id_t
#define uid_t                 __cerbty_uid_t
