USER_TARGET=libhacl.a
USER_CFLAGS=-Wno-unused-variable -Wno-unused-but-set-variable -Wno-parentheses -Wno-unused-parameter
USER_C_FILES=Hacl_Chacha20Poly1305.c Hacl_Poly1305_64.c AEAD_Poly1305_64.c Hacl_Chacha20.c Hacl_Ed25519.c Hacl_Curve25519.c
ALL_C_FILES=Hacl_Hash.c
ALL_H_FILES=Hacl_Hash.h Hacl_Kremlib.h
