FILES= Alphabet.v Tuples.v Grammar.v Automaton.v Validator_complete.v \
       Interpreter.v Interpreter_complete.v Interpreter_correct.v \
       Validator_safe.v Interpreter_safe.v \
       Main.v


coq:
	coqc -noglob $(FILES)

clean:
	rm -rf *.vo
