OTT = ott
COQC = coqc
COQDEP = coqdep
COQDOC = coqdoc
LNGEN = lngen  # optional

RELEASE = /home/jianzhou/release
METALIB = $(RELEASE)/theory/metatheory_8.3
LLVM_LIB = /home/jianzhou/Tools/llvm-2.6/lib/
LLVM_OCAML_LIB = $(LLVM_LIB)/ocaml/
EXTRACTION_LIB = $(RELEASE)/vol/src/Extraction/_build/
