#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct epic_rx_desc {
   unsigned int next ;
};
struct epic_private {
   struct epic_rx_desc *rx_ring ;
   unsigned int rx_skbuff[5] ;
};
extern void abort(void) ;
static void epic_init_ring(struct epic_private *ep ) 
{ 
  int i ;

  {
  i = 0;
  while (i < 5) {
    (ep->rx_ring + i)->next = 10 + (i + 1) * 2;
    ep->rx_skbuff[i] = 0;
    i ++;
  }
  (ep->rx_ring + (i - 1))->next = 10;
  return;
}
}
static int check_rx_ring[5]  = {      12,      14,      16,      18, 
        10};
int main(void) 
{ 
  struct epic_private ep ;
  struct epic_rx_desc rx_ring[5] ;
  int i ;

  {
  i = 0;
  while (i < 5) {
    rx_ring[i].next = 0;
    ep.rx_skbuff[i] = 5;
    i ++;
  }
  ep.rx_ring = rx_ring;
  epic_init_ring(& ep);
  i = 0;
  while (i < 5) {
    if (rx_ring[i].next != (unsigned int )check_rx_ring[i]) {
      abort();
    }
    if (ep.rx_skbuff[i] != 0U) {
      abort();
    }
    i ++;
  }
  return (0);
}
}
