#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

typedef short SInt16;
struct __anonstruct_IOGBounds_1 {
   SInt16 minx ;
   SInt16 maxx ;
   SInt16 miny ;
   SInt16 maxy ;
};
typedef struct __anonstruct_IOGBounds_1 IOGBounds;
int expectedwidth  =    50;
unsigned int *global_vramPtr  =    (unsigned int *)40960;
IOGBounds global_bounds  =    {100, 150, 100, 150};
IOGBounds global_saveRect  =    {75, 175, 75, 175};
extern int ( /* missing proto */  abort)() ;
extern int ( /* missing proto */  exit)() ;
int main(void) 
{ 
  unsigned int *vramPtr ;
  int width ;
  IOGBounds saveRect ;
  IOGBounds bounds ;

  {
  saveRect = global_saveRect;
  bounds = global_bounds;
  if ((int )saveRect.minx < (int )bounds.minx) {
    saveRect.minx = bounds.minx;
  }
  if ((int )saveRect.maxx > (int )bounds.maxx) {
    saveRect.maxx = bounds.maxx;
  }
  vramPtr = global_vramPtr + ((int )saveRect.miny - (int )bounds.miny);
  width = (int )saveRect.maxx - (int )saveRect.minx;
  if (width != expectedwidth) {
    abort();
  }
  exit(0);
}
}
