#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

typedef unsigned long size_t;
extern void abort(void) ;
int global  ;
static void *foo(int p ) 
{ 


  {
  if (p == 0) {
    global ++;
    return (& global);
  }
  return ((void *)((size_t )-1));
}
}
int bar(void) 
{ 
  void *p ;

  {
  p = foo(global);
  if ((unsigned long )p != (unsigned long )((void *)0xffffffffffffffffUL)) {
    return (1);
  }
  global ++;
  return (0);
}
}
int main(void) 
{ 
  int tmp ;

  {
  global = 1;
  tmp = bar();
  if (tmp != 0) {
    abort();
  }
  return (0);
}
}
