#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct __anonstruct_b_1 {
   unsigned int i : 6 ;
   unsigned int j : 11 ;
   unsigned int k : 15 ;
};
struct __anonstruct_c_2 {
   unsigned int i : 5 ;
   unsigned int j : 1 ;
   unsigned int k : 26 ;
};
struct __anonstruct_d_3 {
   unsigned int i : 16 ;
   unsigned int j : 8 ;
   unsigned int k : 8 ;
};
struct __anonstruct_b_1 b  ;
struct __anonstruct_c_2 c  ;
struct __anonstruct_d_3 d  ;
unsigned int ret1(void) 
{ 


  {
  return (b.i);
}
}
unsigned int ret2(void) 
{ 


  {
  return (b.j);
}
}
unsigned int ret3(void) 
{ 


  {
  return (b.k);
}
}
unsigned int ret4(void) 
{ 


  {
  return (c.i);
}
}
unsigned int ret5(void) 
{ 


  {
  return (c.j);
}
}
unsigned int ret6(void) 
{ 


  {
  return (c.k);
}
}
unsigned int ret7(void) 
{ 


  {
  return (d.i);
}
}
unsigned int ret8(void) 
{ 


  {
  return (d.j);
}
}
unsigned int ret9(void) 
{ 


  {
  return (d.k);
}
}
int main(void) 
{ 


  {
  return (0);
}
}
