#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

typedef unsigned long size_t;
extern size_t strlen(char const   *s ) ;
extern int strncmp(char const   *s1 , char const   *s2 , size_t n ) ;
extern void abort(void) ;
char const   *a[16]  = {      "a",      "bc",      "de",      "fgh"};
int foo(char *x , char const   *y , size_t n ) 
{ 
  size_t i ;
  size_t j ;
  size_t tmp ;
  int tmp___0 ;
  size_t tmp___1 ;
  size_t tmp___2 ;

  {
  j = 0;
  i = 0;
  while (i < n) {
    tmp = strlen(a[i]);
    tmp___0 = strncmp(x + j, a[i], tmp);
    if (tmp___0 != 0) {
      return (2);
    }
    tmp___1 = strlen(a[i]);
    j += tmp___1;
    if (y) {
      tmp___2 = strlen(y);
      j += tmp___2;
    }
    i ++;
  }
  return (0);
}
}
int main(void) 
{ 
  int tmp ;

  {
  tmp = foo("abcde", (char const   *)0, 3);
  if (tmp != 0) {
    abort();
  }
  return (0);
}
}
