#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

typedef unsigned long size_t;
typedef short int16_t;
typedef int int32_t;
union __anonunion_v_1 {
   int16_t i ;
   char a[sizeof(int16_t )] ;
};
union __anonunion_v_2 {
   int32_t i ;
   char a[sizeof(int32_t )] ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1,2))) memcpy)(void * __restrict  __dest , void const   * __restrict  __src , size_t __n ) ;
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1))) strlen)(char const   *__s )  __attribute__((__pure__)) ;
extern void abort(void) ;
int a  ;
static void __attribute__((__noclone__))  ( __attribute__((__noinline__)) do_something)(int item ) 
{ 


  {
  a = item;
  return;
}
}
int pack_unpack(char *s , char *p ) 
{ 
  char *send ;
  char *pend ;
  char type ;
  int integer_size ;
  size_t tmp ;
  size_t tmp___0 ;
  char *tmp___1 ;
  union __anonunion_v_1 v ;
  union __anonunion_v_2 v___0 ;

  {
  tmp = strlen(s);
  send = s + tmp;
  tmp___0 = strlen(p);
  pend = p + tmp___0;
  while ((unsigned long )p < (unsigned long )pend) {
    tmp___1 = p;
    p ++;
    type = *tmp___1;
    switch ((int )type) {
    case 115: 
    integer_size = 2;
    goto unpack_integer;
    case 108: 
    integer_size = 4;
    goto unpack_integer;
    unpack_integer: 
    switch (integer_size) {
    case 2: 
    memcpy(v.a, s, sizeof(int16_t ));
    s += sizeof(int16_t );
    do_something(v.i);
    break;
    case 4: 
    memcpy(v___0.a, s, sizeof(int32_t ));
    s += sizeof(int32_t );
    do_something(v___0.i);
    break;
    }
    break;
    }
  }
  return ((int )*s);
}
}
int main(void) 
{ 
  int n ;
  int tmp ;

  {
  tmp = pack_unpack("\200\001\377\376\035\300", "sl");
  n = tmp;
  if (n != 0) {
    abort();
  }
  return (0);
}
}
