#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void exit(int  ) ;
__inline void f(int x ) 
{ 
  int *p[25] ;
  int m[175] ;
  int i ;

  {
  i = 0;
  while (i < 25) {
    p[i] = m + x * i;
    i ++;
  }
  *(p[1] + 0) = 0;
  return;
}
}
int main(void) 
{ 


  {
  f(7);
  exit(0);
}
}
