#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void abort() ;
void ( __attribute__((__noinline__)) bar)(unsigned long long i ) 
{ 


  {
  if (i) {
    abort();
  }
  return;
}
}
static void ( __attribute__((__always_inline__)) foo)(unsigned long long *r ) 
{ 
  int i ;

  {
  i = 0;
  while (! (*r & (1ULL << (63 - i)))) {
    i ++;
  }
  bar(i);
  return;
}
}
void ( __attribute__((__noinline__)) do_test)(unsigned long long *r ) 
{ 
  int i ;

  {
  i = 0;
  while (i < 2) {
    foo(r);
    i ++;
  }
  return;
}
}
int main(void) 
{ 
  unsigned long long r ;

  {
  r = 0x8000000000000001ULL;
  do_test(& r);
  return (0);
}
}
