#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

typedef unsigned long size_t;
typedef unsigned int index_ty;
struct mult_index {
   index_ty index ;
   unsigned int count ;
};
int ( __attribute__((__noinline__)) hash_find_entry)(size_t *result ) 
{ 


  {
  *result = 2;
  return (0);
}
}
extern void abort(void) ;
struct mult_index *( __attribute__((__noinline__)) foo)(size_t n ) ;
static int count  =    0;
struct mult_index *( __attribute__((__noinline__)) foo)(size_t n ) 
{ 
  int tmp ;

  {
  tmp = count;
  count ++;
  if (tmp > 0) {
    abort();
  }
  return (0);
}
}
int main(void) 
{ 
  size_t nitems ;
  size_t list ;
  size_t len2 ;
  struct mult_index *destptr ;
  struct mult_index *dest ;
  size_t new_max ;
  size_t tmp ;

  {
  nitems = 0;
  while (1) {
    hash_find_entry(& list);
    len2 = list;
    new_max = nitems + len2;
    if (new_max != len2) {
      break;
    }
    dest = foo(new_max);
    destptr = dest;
    while (1) {
      tmp = len2;
      len2 --;
      if (! tmp) {
        break;
      }
      destptr ++;
    }
    nitems = destptr - dest;
  }
  return (0);
}
}
