#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct __anonstruct_A_1 {
   int i ;
   int dummy ;
};
typedef struct __anonstruct_A_1 A;
extern void abort() ;
__inline A foo(A const   *p , A const   *q ) 
{ 
  A __constr_expr_0 ;

  {
  __constr_expr_0.i = p->i + q->i;
  __constr_expr_0.dummy = 0;
  return (__constr_expr_0);
}
}
void bar(A * __restrict  p ) 
{ 


  {
  *p = foo(p, p);
  if (p->i != 2) {
    abort();
  }
  return;
}
}
int main(void) 
{ 
  A a ;

  {
  a.i = 1;
  a.dummy = 0;
  bar(& a);
  return (0);
}
}
