Jnote01_struct-race.pdf: Jnote01_struct-race.tex
	pdflatex Jnote01_struct-race.tex

Jnote02-2012-10-9_effective-types.pdf: Jnote02-2012-10-9_effective-types.tex
	pdflatex Jnote02-2012-10-9_effective-types.tex
