(* Generated by Lem from ocaml_generated/loc.lem. *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import String.
Require Import Program.Wf.

Require Import coqharness.

Open Scope nat_scope.
Open Scope string_scope.

Require Import lem_pervasives.
Require Export lem_pervasives.

(* 

Inductive t : Type := .
Definition t_default: t  := DAEMON. *)
(* [?]: removed value specification. *)

(* [?]: removed value specification. *)

(* [?]: removed value specification. *)

(* [?]: removed value specification. *)

(* [?]: removed value specification. *)

(* [?]: removed value specification. *)


Class Located (a: Type): Type := {
  locOf:a -> unit
}.

(* [?]: removed value specification. *)

(* [?]: removed value specification. *)

