exception Error

type token = 
  | XOR_ASSIGN of (Cabs0.cabsloc)
  | WHILE of (Cabs0.cabsloc)
  | VOLATILE of (Cabs0.cabsloc)
  | VOID of (Cabs0.cabsloc)
  | VAR_NAME of (string * Pre_parser_aux.identifier_type ref * Cabs0.cabsloc)
  | UNSIGNED of (Cabs0.cabsloc)
  | UNKNOWN_NAME of (string * Pre_parser_aux.identifier_type ref * Cabs0.cabsloc)
  | UNION of (Cabs0.cabsloc)
  | TYPEDEF_NAME of (string * Pre_parser_aux.identifier_type ref * Cabs0.cabsloc)
  | TYPEDEF of (Cabs0.cabsloc)
  | TILDE of (Cabs0.cabsloc)
  | SWITCH of (Cabs0.cabsloc)
  | SUB_ASSIGN of (Cabs0.cabsloc)
  | STRUCT of (Cabs0.cabsloc)
  | STRING_LITERAL of (string * Cabs0.cabsloc)
  | STATIC of (Cabs0.cabsloc)
  | STAR of (Cabs0.cabsloc)
  | SLASH of (Cabs0.cabsloc)
  | SIZEOF of (Cabs0.cabsloc)
  | SIGNED of (Cabs0.cabsloc)
  | SHORT of (Cabs0.cabsloc)
  | SEMICOLON of (Cabs0.cabsloc)
  | RPAREN of (Cabs0.cabsloc)
  | RIGHT_ASSIGN of (Cabs0.cabsloc)
  | RIGHT of (Cabs0.cabsloc)
  | RETURN of (Cabs0.cabsloc)
  | RESTRICT of (Cabs0.cabsloc)
  | REGISTER of (Cabs0.cabsloc)
  | RBRACK of (Cabs0.cabsloc)
  | RBRACE of (Cabs0.cabsloc)
  | QUESTION of (Cabs0.cabsloc)
  | PTR of (Cabs0.cabsloc)
  | PLUS of (Cabs0.cabsloc)
  | PERCENT of (Cabs0.cabsloc)
  | OR_ASSIGN of (Cabs0.cabsloc)
  | NEQ of (Cabs0.cabsloc)
  | MUL_ASSIGN of (Cabs0.cabsloc)
  | MOD_ASSIGN of (Cabs0.cabsloc)
  | MINUS of (Cabs0.cabsloc)
  | LT of (Cabs0.cabsloc)
  | LPAREN of (Cabs0.cabsloc)
  | LONG of (Cabs0.cabsloc)
  | LEQ of (Cabs0.cabsloc)
  | LEFT_ASSIGN of (Cabs0.cabsloc)
  | LEFT of (Cabs0.cabsloc)
  | LBRACK of (Cabs0.cabsloc)
  | LBRACE of (Cabs0.cabsloc)
  | INT of (Cabs0.cabsloc)
  | INLINE of (Cabs0.cabsloc)
  | INC of (Cabs0.cabsloc)
  | IF of (Cabs0.cabsloc)
  | HAT of (Cabs0.cabsloc)
  | GT of (Cabs0.cabsloc)
  | GOTO of (Cabs0.cabsloc)
  | GEQ of (Cabs0.cabsloc)
  | FOR of (Cabs0.cabsloc)
  | FLOAT of (Cabs0.cabsloc)
  | EXTERN of (Cabs0.cabsloc)
  | EQEQ of (Cabs0.cabsloc)
  | EQ of (Cabs0.cabsloc)
  | EOF
  | ENUM of (Cabs0.cabsloc)
  | ELSE of (Cabs0.cabsloc)
  | ELLIPSIS of (Cabs0.cabsloc)
  | DOUBLE of (Cabs0.cabsloc)
  | DOT of (Cabs0.cabsloc)
  | DO of (Cabs0.cabsloc)
  | DIV_ASSIGN of (Cabs0.cabsloc)
  | DEFAULT of (Cabs0.cabsloc)
  | DEC of (Cabs0.cabsloc)
  | CONTINUE of (Cabs0.cabsloc)
  | CONSTANT of (Cabs0.constant * Cabs0.cabsloc)
  | CONST of (Cabs0.cabsloc)
  | COMMA of (Cabs0.cabsloc)
  | COLON of (Cabs0.cabsloc)
  | CHAR of (Cabs0.cabsloc)
  | CASE of (Cabs0.cabsloc)
  | BUILTIN_VA_ARG of (Cabs0.cabsloc)
  | BREAK of (Cabs0.cabsloc)
  | BOOL of (Cabs0.cabsloc)
  | BARBAR of (Cabs0.cabsloc)
  | BAR of (Cabs0.cabsloc)
  | BANG of (Cabs0.cabsloc)
  | AUTO of (Cabs0.cabsloc)
  | AND_ASSIGN of (Cabs0.cabsloc)
  | ANDAND of (Cabs0.cabsloc)
  | AND of (Cabs0.cabsloc)
  | ADD_ASSIGN of (Cabs0.cabsloc)


val translation_unit_file: (Lexing.lexbuf -> token) -> Lexing.lexbuf -> (unit)
