import $ from 'jquery'
import './css/scheme.css'
import './css/goldenlayout-base.css'
import './css/goldenlayout-light-theme.css'
import './css/codemirror.css'
import './css/style.css'
import './js/gas.js'
import './js/clike.js'
import './js/ast.js'
import './js/core.js'
import './js/ocaml.js'
import './js/placeholder.js'
import './js/panzoom.js'
import { onLoad } from './ui'

$(window).ready(onLoad)