#!/usr/bin/env -S bash -euo pipefail
echo $@
rm -rf tmp-los/*
cp $@  tmp-los
cd tmp-los && rename 's/.lem/.ml/'  *.lem && sloccount --details *.ml

#for i in `ls *.ml` ; do sloccount --details "$i" ; done  #