let bound2MD x y z = failwith "bound2MD:na"
let get_reg_metadata x y z w = failwith "get_reg_metadata:na"

let assert_mptr_fid = "@__loadDereferenceCheck"
let fake_id = "%-1"
let get_mmetadata_fid = "@__hashLoadBaseBound"
let get_mmetadata_base_fid = "@__hashLoadBase"
let get_mmetadata_bound_fid = "@__hashLoadBound"
let set_mmetadata_fid = "@__hashStoreBaseBound"
let set_shadowstack_base_fid = "@__softboundcetswithss_store_base_shadow_stack"
let set_shadowstack_bound_fid = "@__softboundcetswithss_store_bound_shadow_stack"
let get_shadowstack_base_fid = "@__softboundcetswithss_load_base_shadow_stack"
let get_shadowstack_bound_fid = "@__softboundcetswithss_load_bound_shadow_stack"
let allocate_shadowstack_fid = 
  "@__softboundcetswithss_allocate_shadow_stack_space"
let free_shadowstack_fid = "@__softboundcetswithss_deallocate_shadow_stack_space"

let gveq x y z = failwith "SBpass.gveq is na."

let wrapper_fid fid = 
  let fn = Coq_pretty_printer.getRealName fid in
match fn with
| "main" -> "@softbound_pseudo_main"
| "system"
| "setreuid"
| "mkstemp"
| "getuid"
| "getrlimit"
| "setrlimit"
| "qsort"
| "fread"
| "umask"
| "mkdir"
| "chroot"
| "rmdir"
| "stat"
| "fputc"
| "fileno"
| "fgetc"
| "strncmp"
| "log"
| "fwrite"
| "fabs"
| "fabsf"
| "bcopy"
| "strlen"
| "globfree"
| "my_mmap"
| "vprintf"
| "crypt"
| "usleep"
| "strftime"
| "select"
| "alphasort"
| "getnameinfo"
| "fchmod"
| "setsockopt"
| "munmap"
| "alarm"
| "realpath"
| "getdtablesize"
| "getusershell"
| "endusershell"
| "_exit"
| "wait3"
| "recv"
| "htonl"
| "htons"
| "ntohs"
| "accept"
| "waitpid"
| "getpid"
| "listen"
| "closelog"
| "setenv"
| "setuid"
| "setgid"
| "send"
| "openlog"
| "lseek"
| "write"
| "read"
| "open"
| "close"
| "unlink"
| "connect"
| "bind"
| "socket"
| "inet_ntoa"
| "getsockname"
| "getpeername"
| "inet_addr"
| "strerror"
| "__ctype_tolower_loc"
| "tolower"
| "toupper"
| "__ctype_toupper_loc"
| "__ctype_b_loc"
| "__errno_location"
| "atexit"
| "lstat"
| "chmod"
| "getopt_long"
| "getopt"
| "getenv"
| "setbuf"
| "difftime"
| "ctime"
| "utime"
| "lrand48"
| "free"
| "drand48"
| "time"
| "localtime"
| "gmtime"
| "times"
| "putchar"
| "strcmp"
| "atoi"
| "atol"
| "puts"
| "rand"
| "abort"
| "malloc"
| "realloc"
| "calloc"
| "exit"
| "clock"
| "fclose"
| "signal"
| "gethostname"
| "sigaddset"
| "tzset"
| "sigprocmask"
| "sigfillset"
| "daemon"
| "seteuid"
| "initgroups"
| "setegid"
| "sigemptyset"
| "memcmp"
| "strstr"
| "strncpy"
| "strrchr"
| "strcpy"
| "strchr"
| "strncat"
| "strcat"
| "strcspn"
| "strspn"
| "strdup"
| "__strdup"
| "strtok"
| "perror"
| "fgets"
| "gets"
| "strpbrk"
| "__strpbrk_c3"
| "strncasecmp"
| "strcasecmp"
| "memchr"
| "chdir"
| "isatty"
| "chown"
| "getcwd"
| "sleep"
| "rename"
| "closedir"
| "opendir"
| "readdir"
| "rewind"
| "pclose"
| "popen"
| "ftruncate"
| "fseek"
| "fdopen"
| "fopen"
| "fputs"
| "fflush"
| "fstat"
| "ftell"
| "ferror"
| "tmpfile"
| "ldexp"
| "exp"
| "cosl"
| "cosf"
| "cos"
| "sinl"
| "sinf"
| "sin"
| "log10"
| "tanl"
| "tanf"
| "tan"
| "pow"
| "srand48"
| "srand"
| "sqrt"
| "floor"
| "ceilf"
| "ceil"
| "floorf"
| "exp2"
| "expf"
| "sqrtf"
| "atan2"
| "acos"
| "remove"
| "feof"
| "atof"
| "getttyent"
| "glob"
| "getservbyname"
| "getaddrinfo"
| "gethostbyname"
| "gethostbyaddr"
| "scandir"
| "getpwnam"
| "getgrgid"
| "getpwuid"
| "new_realloc"
| "new_memcpy"
| "changed_realloc"
| "strtol"
| "strtoul" ->
      "@softbound_" ^ fn
| _ -> fid

