#include "cerberus.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void abort(void) ;
extern void exit(int  ) ;
int main(void) 
{ 
  int a ;
  int b ;
  int c ;
  int *pa ;
  int *pb ;
  int *pc ;
  int **ppa ;
  int **ppb ;
  int **ppc ;
  int i ;
  int x ;
  int y ;
  int z ;
  int tmp ;

  {
  a = 10;
  b = 20;
  c = 30;
  pa = & a;
  pb = & b;
  pc = & c;
  ppa = & pa;
  ppb = & pb;
  ppc = & pc;
  x = 0;
  y = 0;
  z = 0;
  i = 0;
  while (i < 10) {
    if ((unsigned long )pa == (unsigned long )(& a)) {
      pa = & b;
    } else {
      pa = & a;
    }
    while (1) {
      tmp = *pa;
      (*pa) --;
      if (! tmp) {
        break;
      }
      x ++;
      if (*pa < 3) {
        break;
      } else {
        pa = & b;
      }
    }
    x ++;
    pa = & b;
    i ++;
  }
  if ((*pa != -5 || *pb != -5) || x != 43) {
    abort();
  }
  exit(0);
}
}
